name: Test Twitter Clone

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the containers
      run: docker-compose build

    - name: Start containers
      run: |
        docker-compose up -d
        sleep 10  # Wait for containers to be ready

    - name: Check running containers
      run: docker-compose ps

    - name: Generate test data
      run: |
        docker-compose exec -T web python project/tests/generate_test_data.py \
          "postgresql://twitter_user:twitter_password@db:5432/twitter_dev" 10 100

    - name: Run tests
      run: |
        docker-compose exec -T web python -m unittest project/tests/test_app.py -v

    - name: Display logs on failure
      if: failure()
      run: docker-compose logs

    - name: Stop containers
      if: always()
      run: docker-compose down 